FROM golang:1.19.3-alpine AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=1

WORKDIR /build

COPY ../ /build/

RUN go mod download

RUN go build http_server_week2/ -o http_server

WORKDIR /dist

RUN cp /build/http_server /dist/http_server


FROM ubuntu:latest
RUN mkdir /app
COPY /app/http_server --from=builder/dist

RUN chmod +x /app/http_server
WORKDIR /app
EXPOSE 80
CMD [ "/app/http_server" ]