apiVersion: v1
kind: Pod
metadata:
  name: week8
  labels: 
    app: httpserver
spec:
  containers:
    - name: week8
      image: bryanwsh330/httpserver:v2.0
      args:
        - /app/http_server
      volumeMounts:
        - name: configs
          mountPath: /app/configs/config.json
          subPath: config.json
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - pkill
              - httpserver
  volumes:
    - name: configs
      configMap:
        name: week8-config